openapi: 3.0.1
info:
  title: ACME - API de Análise de Fraudes
  description: |
    # ACME Frauds API

    Esta API é responsável por fornecer a classificação de risco de um cliente para análise de fraude.

    ---
    ## Desenvolvedores
    - Equipe ACME - Squad de Fraudes
  version: 1.0.0

tags:
  - name: analise-fraude
    description: "Análise de risco de cliente para prevenção de fraude"

paths:
  /v1/analise:
    post:
      tags:
        - analise-fraude
      summary: Realiza a análise de risco de um cliente
      description: |
        Realiza a análise de risco do cliente com base no ID da apólice e do cliente.
      operationId: analisarRisco
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnaliseFraudeRequest"
      responses:
        '200':
          description: Análise de risco realizada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnaliseFraudeResponse"
        '400':
          description: Requisição inválida

components:
  schemas:
    AnaliseFraudeRequest:
      type: object
      properties:
        apoliceId:
          type: string
          format: uuid
          example: "9fa85f64-5717-4562-b3fc-2c963f66afa6"
        clienteId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    AnaliseFraudeResponse:
      type: object
      properties:
        apoliceId:
          type: string
          format: uuid
          example: "9fa85f64-5717-4562-b3fc-2c963f66afa6"
        clienteId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        dataAnalise:
          type: string
          format: date-time
          example: "2025-08-27T10:30:00-03:00"
        classificacao:
          $ref: "#/components/schemas/TipoCliente"
        ocorrencias:
          type: array
          items:
            $ref: "#/components/schemas/Ocorrencia"

    Ocorrencia:
      type: object
      properties:
        produtoId:
          type: string
          format: uuid
          example: "8b9a7c6c-5e4d-3b2a-1c0f-00d9f8e7d6c5"
        tipo:
          $ref: "#/components/schemas/TipoCliente"
        descricao:
          type: string
          example: "Histórico de sinistros nos últimos 12 meses"
        dataCriacao:
          type: string
          format: date-time
          example: "2025-08-27T09:00:00-03:00"
        dataAtualizacao:
          type: string
          format: date-time
          example: "2025-08-27T09:30:00-03:00"

    TipoCliente:
      type: string
      enum:
        - REGULAR
        - ALTO_RISCO
        - PREFERENCIAL
        - SEM_INFORMACAO
      example: REGULAR

    ApoliceConsulta:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "9fa85f64-5717-4562-b3fc-2c963f66afa6"
        clienteId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        produtoId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        categoria:
          $ref: "#/components/schemas/CategoriaSeguro"
        metodoPagemento:
          $ref: "#/components/schemas/TipoPagamento"
        status:
          $ref: "#/components/schemas/Estado"
        dataCriacao:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"
        dataFinalizacao:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"
        valorTotalPremioMensal:
          type: number
          format: double
          example: 200.00
        valorSegurado:
          type: number
          format: double
          example: 100000.00
        cobertura:
          $ref: "#/components/schemas/Cobertura"
        assistencias:
          type: array
          items:
            type: string
          example:
            - "Guincho até 250km"
            - "Troca de Óleo"
            - "Chaveiro 24h"
        historico:
          type: array
          items:
            $ref: "#/components/schemas/Historico"

    Apolice:
      type: object
      properties:
        clienteId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        produtoId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        categoria:
          $ref: "#/components/schemas/CategoriaSeguro"
        origem:
          $ref: "#/components/schemas/TipoCanalVendas"
        metodoPagemento:
          $ref: "#/components/schemas/TipoPagamento"
        valorTotalPremioMensal:
          type: number
          format: double
          example: 150.00
        valorSegurado:
          type: number
          format: double
          example: 100000.00
        cobertura:
          $ref: "#/components/schemas/Cobertura"
        assistencias:
          type: array
          items:
            type: string
          example:
            - "Guincho até 250km"
            - "Troca de Óleo"
            - "Chaveiro 24h"

    ApoliceResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "9fa85f64-5717-4562-b3fc-2c963f66afa6"
        dataCriacao:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"

    Cobertura:
      type: object
      properties:
        roubo:
          type: number
          format: double
          example: 100000.25
        perdaTotal:
          type: number
          format: double
          example: 100000.25
        colisaoTerceiros:
          type: number
          format: double
          example: 75000.00

    TipoCanalVendas:
      type: string
      enum:
        - MOBILE
        - WHATSAPP
        - WEB_SITE
      example: MOBILE

    TipoPagamento:
      type: string
      enum:
        - CARTAO_CREDITO
        - DEBITO_EM_CONTA
        - BOLETO
        - PIX
      example: CARTAO_CREDITO

    CategoriaSeguro:
      type: string
      enum:
        - VIDA
        - AUTO
        - RESIDENCIAL
        - EMPRESARIAL
      example: AUTO

    Estado:
      type: string
      enum:
        - RECEBIDO
        - VALIDADO
        - PENDENTE
        - REJEITADO
        - APROVADO
        - CANCELADA
      example: RECEBIDO

    Historico:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Estado'
        dataCriacao:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"